### ISSUE TITLE
Add all documentation updates here!

### ISSUE THREAD

**Issue by smarabattula** [varundeepakgudhe/auto_anki#8]

**Comment by smarabattula** [comment]
Update document for Virtual Env Setup

Create the virtual environment: python -m venv myenv
Activate the virtual environment: source myenv/bin/activate.

In my local, activate script is present under "Script" folder. Update README.md with the correct instruction

**Comment by smarabattula** [comment]
Installation Step 5. Install the project as a Python package: `pip install .` not really required

**Comment by MatthewSills** [comment]
Updated Code Coverage install and run instructions.

Updated Code Coverage Chart.

**Comment by MatthewSills** [comment]
Added docker run instructions to Readme

**Comment by smarabattula** [comment]
The PyCCO documentation was updated. The index file didn't get generated, so @smarabattula created latest code documentation in HTML and PDF.

**Comment by varundeepakgudhe** [comment]
Generated and Added DOI badge in Readme

**Comment by varundeepakgudhe** [comment]
Added the introduction, what, why, quick start, features, contribute, roadmap, contact, funding, acknowledgement, citation in the document

**Comment by varundeepakgudhe** [comment]
Updated the table of contents, video, use cases , screenshots
